### ISSUE TITLE
The design is not working at all in Safari browser, causing issue in Mac Word Desktop

### ISSUE THREAD

**Issue by HiranPeri** [OfficeDev/Office-Add-in-UX-Design-Patterns-Code#1]
Most of the elements used here are using flex based design which is yet not fully supported..
the design looks entirely different in safari as compared to what I can see in IE-11, Firfox and Chrome.

Adding further information, It works a little on Safari 9.0 but not at all in Safari 5.1.7.
And Safari 5.1.7 is set minium supported version for office add-ins in client software requirements.

**Comment by WrathOfZombies** [comment]
Thank you for the feedback. You are right about 5.1.7 not having support for flex boxes. We will look into the issue and get back to you.

**Comment by HiranPeri** [comment]
Okay.. But then the First run screens & Walk-through design is also not working in Safari 9.x (Tested on Mac).

_The only change that I did in walk through screen was instead of image, I kept div (which also contains image in it)._

**Comment by WrathOfZombies** [comment]
I would suggest trying it inside of an Add-in. The browser context that the add-in runs in, is different and it works as expected in that. We have noted some browser compatibility issues and we will be resolving them in future revisions of the project.

If you wish to test within a browser I would suggest IE11, Edge or Google Chrome as the top choices.

**Comment by HiranPeri** [comment]
I understand that, the add-in design works perfectly fine for systems having office 2013 or 2016 with IE-11, Edge, Chrome and Firefox.

But thinking from customer's point of view, all of them will not have IE 11 or edge for instance and all of them will not have Windows OS either especially when the add-in is to be used by specific user group in USA (where Mac system is quite common).

For now we have restricted our add-in to work on Mac version so that should be fine. But the First run screen, Add-In brand bar is not working in older version of IE (10 & 9). At least it should support IE-9 as that's default browser that comes with Windows - 7.

Can you tell me, how sooner these bugs will be fixed?

**Comment by Reezaali** [comment]
Thanks for working with us on this issue. We're updating the css files to include the webkit prefixes. Also, since you used this in an SPA, you need to ensure the height of the container DIVs are reset correctly. Thanks!
