### ISSUE TITLE
Inline Notification improvements

### ISSUE THREAD

**Issue by MartinSSeifert** [OfficeDev/Office-Add-in-UX-Design-Patterns-Code#3]
Our first test users came with feedback that they thought there was a typo with the ‘i ’ that is indented at the beginning of the informational message. To them it looked like the i was part of the message. 
 
So we are strongly thinking about changing the ‘i ‘ to something like ms-Icon—infoCircle even though it might be a little small in this context.

Here is how the sample could look like:
![capture](https://cloud.githubusercontent.com/assets/19793161/16336793/4e984358-3a10-11e6-891c-cc133f1679d5.PNG)

**Comment by Reezaali** [comment]
Thank you MartinSSeifert for your feedback. I'll work with my design team to get this approved and integrated into our code sample. Please keep the feedback coming! If you would like to make the change to the code yourself, please feel free to do so and then submit a pull request. Thanks!

**Comment by Reezaali** [comment]
I've made the change and pushed it live. Thanks very much for your feedback, and please keep it coming!
