### ISSUE TITLE
Examples are using old UI Fabric 2.1.0

### ISSUE THREAD

**Issue by barisbikmaz** [OfficeDev/Office-Add-in-UX-Design-Patterns-Code#4]
Please update examples to the newest fabric version. I think some css bugs are fixed. Why not always using the newest fabric? For instance you could use node and reference the fabric node package to be up to date.

**Comment by Reezaali** [comment]
Thanks for reporting your issue @barisbikmaz! Did you encounter CSS issues with the samples? 

We've started updating some samples with the latest version. Those should be released next week or the week after that. 

We're also planning to update all the samples to use Fabric 3.0 in Aug/Sept. Currently the team's focus is on delivering all the new patterns our design team has put together. After that we'll update and retest the samples. Thanks!

**Comment by barisbikmaz** [comment]
Thanks @Reezaali for the info. Yes as an example the inline message info style is using the success style. I think that could be a minor bug.

**Comment by Reezaali** [comment]
@barisbikmaz we just released some of the navigation patterns which we found needed a specific version of Fabric. We're not going to update the versions of Fabric just yet. 

As an option, if you update and test some of the patterns with newer versions of Fabric, you can submit a pull request. Thanks!
